INSERT INTO FIELDS VALUES( 309,'AMAHORO',20,'HUYE','CLAY');
INSERT INTO FIELDS VALUES( 209,'HINGA WEZA',36,'KAYONZA','LOAMY');
INSERT INTO FIELDS VALUES( 109,'RAMIRO',17,'BUGESERA','SANDY');
COMMIT;