SELECT CUSTOMERS.CUSTOMERID, ADDRESS
FROM CUSTOMERS
INNER JOIN SALES ON SALES.CUSTOMERID = CUSTOMERS.CUSTOMERID;
COMMIT;
SELECT CUSTOMERS.CUSTOMERID, CUSTOMER_NAME, ADDRESS
FROM CUSTOMERS
LEFT JOIN SALES
ON SALES.CUSTOMERID = CUSTOMERS.CUSTOMERID;
COMMIT;
SELECT CUSTOMERS.CUSTOMERID, CUSTOMER_NAME, ADDRESS
FROM CUSTOMERS
RIGHT JOIN SALES
ON SALES.CUSTOMERID = CUSTOMERS.CUSTOMERID;
COMMIT;
SELECT CUSTOMERS.CUSTOMERID, CUSTOMER_NAME
FROM CUSTOMERS
FULL OUTER JOIN CROPS
ON CUSTOMERS.CUSTOMERID = CROPS.CROPID
WHERE CROPNAME='FRUITS';
COMMIT;